using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using SideXC.WebUI.Classes;
using SideXC.WebUI.Data;
using SideXC.WebUI.Models.Human_Resources;
using SideXC.WebUI.Models.Local;
using SideXC.WebUI.Models.Map;
using SideXC.WebUI.Models.Security;

namespace SideXC.WebUI.Controllers.HumanResources
{
    public class EmployeesController : BaseController
    {
        private readonly ApplicationDbContext _context;
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="context"></param>
        public EmployeesController(ApplicationDbContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Index view
        /// </summary>
        /// <returns></returns>
        [Authorization]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.Include(p=> p.Position).Include(e=> e.Contacts).ThenInclude(c=> c.ContactType).Include(a=> a.Address).ThenInclude(n=> n.Neighborhood).ThenInclude(c=> c.City).ThenInclude(s=> s.State).ThenInclude(c=> c.Country).ToListAsync());
        }
        /// <summary>
        /// Create view
        /// </summary>
        /// <returns></returns>
        [Authorization]
        public IActionResult Create()
        {
            var listPositions = _context.Positions.Where(c => c.Active == true).ToList();
            var listProfiles = _context.Profiles.Where(c => c.Active == true).ToList();
            var listContactTypes = _context.ContactTypes.Where(c => c.Active == true).ToList();
            ViewBag.PasswordAutoGenerated = Common.GetRandomAlphanumericString(8);
            ViewBag.Positions = new SelectList(listPositions, "Id", "Description", 0);
            ViewBag.Profiles = new SelectList(listProfiles, "Id", "Description", 0);
            ViewBag.ContactTypes = new SelectList(listContactTypes, "Id", "Description", 0);
            return View();
        }
        /// <summary>
        /// Create post
        /// </summary>
        /// <param name="employee"></param>
        /// <param name="collection"></param>
        /// <returns></returns>
        [Authorization]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Employee employee, IFormCollection collection)
        {           
            var name = collection["Name"].ToString();
            var lastName1 = collection["LastName1"].ToString();
            var lastName2 = collection["LastName2"].ToString();
            var positionId = int.Parse(collection["ddPositions"].ToString());
            var grossSalary = double.Parse(collection["GrossSalary"].ToString());
            var netSalary = double.Parse(collection["NetSalary"].ToString());
            var dailySalary = double.Parse(collection["DailySalary"].ToString());
            var integratedDailySalary = double.Parse(collection["IntegratedDailySalary"].ToString());
            var street = collection["txtStreet"].ToString();
            var externalNumber = collection["txtExternalNumber"].ToString();
            var internalNumber = collection["txtInternalNumber"].ToString();
            var ziCode = collection["txtZipCode"].ToString();
            var coloniaId = int.Parse(collection["ddColonia"].ToString());
            var email = collection["txtEmail"].ToString();
            var password = collection["txtPassword"].ToString();
            var profileId = int.Parse(collection["ddProfile"].ToString());
            var profile = _context.Profiles.FirstOrDefault(p=> p.Id == profileId);
            var contacts = collection["hddContacts"].ToString();
            var listContacts = JsonConvert.DeserializeObject<List<lContacts>>(contacts).ToList();
            var position = _context.Positions.FirstOrDefault(p => p.Id == positionId);
            var colonia = _context.Neighborhoods.Include(c => c.City).ThenInclude(s => s.State).ThenInclude(c => c.Country).FirstOrDefault(n => n.Id == coloniaId);
            // Create address
            var address = new Address()
            {
                Street = street,
                ExternalNumber = externalNumber,
                InternalNumber = internalNumber,
                Neighborhood = colonia,
                Active = true,
                Created = DateTime.Now,
                CreatedBy = UserLogged,
                Modified = DateTime.Now,
                ModifiedBy = UserLogged
            };
            //Create contacts
            foreach(var item in listContacts)
            {
                var contactType = _context.ContactTypes.FirstOrDefault(c=> c.Id == item.ContactTypeId);
                var contact = new EmployeeContact()
                {
                    ContactType = contactType,
                    Description = item.Description,                    
                    Created = DateTime.Now,
                    CreatedBy = UserLogged,
                    Modified = DateTime.Now,
                    ModifiedBy = UserLogged
                };
                employee.AddContact(contact);
            }
            //create users
            var existsUser = _context.ClientUsers.FirstOrDefault(e => e.Email == email);
            var statusClient = _context.StatusClientUsers.FirstOrDefault(s=> s.Id == 2);
            var newUser = new ApplicationUser() {
                UID = Guid.NewGuid(),
                Email = email,
                PasswordHash = password,
                LockoutEnabled = false,
                EmailConfirmed = false,
                AccessFailedCount = 0,
                Created = DateTime.Now,
                Modified = DateTime.Now
            };
            //Valida si existe usuario
            if(existsUser != null)
            {
                ModelState.AddModelError("err", "Ya existe el empleado con este correo.");
                var listPositions = _context.Positions.Where(c => c.Active == true).ToList();
                var listProfiles = _context.Profiles.Where(c => c.Active == true).ToList();
                var listContactTypes = _context.ContactTypes.Where(c => c.Active == true).ToList();
                ViewBag.PasswordAutoGenerated = Common.GetRandomAlphanumericString(8);
                ViewBag.Positions = new SelectList(listPositions, "Id", "Description", 0);
                ViewBag.Profiles = new SelectList(listProfiles, "Id", "Description", 0);
                ViewBag.ContactTypes = new SelectList(listContactTypes, "Id", "Description", 0);
                return View(employee);
            }
            _context.Add(newUser);
            //Llena datos de empleado
            employee.Name = name;
            employee.LastName1 = lastName1;
            employee.LastName2 = lastName2;
            employee.EmployeeNumber = CreateEmployeeConsecutive(UserLogged); 
            employee.GrossSalary = grossSalary;
            employee.NetSalary = netSalary;
            employee.DailySalary = dailySalary;
            employee.IntegratedDailySalary = integratedDailySalary;
            employee.Position = position;
            employee.Address = address;
            employee.PhotUrl = string.Empty;
            employee.Active = true;
            employee.ClientUser = newUser;
            employee.Created = DateTime.Now;
            employee.CreatedBy = UserLogged;
            employee.Modified = DateTime.Now;
            employee.ModifiedBy = UserLogged;
            _context.Add(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        /// <summary>
        /// Consecutivo de número de empleado
        /// </summary>
        /// <param name="userLogged"></param>
        /// <returns></returns>
        private string CreateEmployeeConsecutive(ApplicationUser userLogged)
        {
            var hayConsecutivo = _context.EmployeeConsecutives.FirstOrDefault(s => s.Created == DateTime.Today);
            EmployeeConsecutive consecutive;
            if (hayConsecutivo == null)
            {
                consecutive = new EmployeeConsecutive()
                {
                    Folio = 1,
                    Created = DateTime.Today,
                    CreatedBy = userLogged,
                    Modified = DateTime.Today,
                    ModifiedBy = userLogged
                };
                _context.Add(consecutive);
                _context.SaveChanges();
            }
            else
            {
                consecutive = hayConsecutivo;
                consecutive.Folio += 1;
                _context.SaveChanges();
            }
            return string.Concat(DateTime.Today.Year.ToString().PadLeft(4, '0'),
                                    DateTime.Today.Month.ToString().PadLeft(2, '0'),
                                    DateTime.Today.Day.ToString().PadLeft(2, '0'),
                                    consecutive.Folio.ToString().PadLeft(3, '0')
                                    );
        }
        /// <summary>
        /// Edit view
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorization]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) { return NotFound(); }
            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)  { return NotFound(); }
            return View(employee);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="employee"></param>
        /// <returns></returns>
        [Authorization]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,LastName1,LastName2,PhotUrl,GrossSalary,NetSalary,DailySalary,IntegratedDailySalary,Active,Created,Modified")] Employee employee)
        {
            if (id != employee.Id) { return NotFound(); }

            if (ModelState.IsValid)
            {
                try
                {
                    employee.Modified = DateTime.Now;
                    employee.ModifiedBy = UserLogged;
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id)) { return NotFound(); }
                    else { throw; }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }
        /// <summary>
        /// Valida empleado existente
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }
        /// <summary>
        /// Buscar codigo postal
        /// </summary>
        /// <param name="zipcode"></param>
        /// <returns></returns>
        public string BuscarCodigoPostal(string zipcode)
        {
            var colonias = _context.Neighborhoods.Where(m => m.ZipCode == zipcode).Include(a => a.City).ThenInclude(t => t.State).ThenInclude(s => s.Country).ToList();
            var query = (
                            from c in colonias
                            select new
                            {
                                idColonia = c.Id,
                                Colonia = c.Description,
                                Municipio = c.City?.Description,
                                Estado = c.City?.State?.Description,
                                Pais = c.City?.State?.Country?.Description
                            }
                ).ToList();
            return JsonConvert.SerializeObject(query);
        }
    }
}
